services:
  server:
    build:
      context: ./CRM_server
    container_name: titan_server
#    ports:
#      - "5000:5000"
    networks:
      - titan_network
    environment:
      - NODE_ENV=production

  crm_frontend:
    build:
      context: ./CRM_frontend
    container_name: titan_frontend
#    ports:
#      - "8080:80"
    networks:
      - titan_network

  caddy:
    image: caddy:alpine
    container_name: titan_caddy
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP (for redirect)
      - "443:443"    # HTTPS
#      - "5000:5000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - titan_network

networks:
  titan_network:
    driver: bridge
