services:
  crm_frontend:
    build:
      context: ./CRM_frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - crm_backend

  crm_backend:
    build:
      context: ./CRM_server
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - crm_frontend
      - crm_backend

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
